cache:
  paths:
    - maven.repository/
 
deployTag:
  stage: deploy
  image: maven:3.6-jdk-11
  script:
    - 'mvn -P ci --batch-mode -Dmaven.repo.local=maven.repository -fn -DskipTests -s ci_settings.xml deploy'
  allow_failure: true
  only:
    - tags
  except:
    - branches

testCoverage:
  stage: test
  image: maven:3.6-jdk-11
  script:
    - 'mvn -P ci --batch-mode -Dmaven.repo.local=maven.repository -fn clean install'
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"
        - "**/target/failsafe-reports/TEST-*.xml"
  allow_failure: true
  except:
    - tags

generate-coverage:
  stage: deploy
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
  needs: ["testCoverage"]
  dependencies:
    - testCoverage
  artifacts:
    reports:
      cobertura: target/site/cobertura.xml
  allow_failure: true
  except:
    - tags

publish:
  stage: deploy
  script:
    - mv target/generated-docs public
  artifacts:
    paths:
      - public
  allow_failure: true
  except:
    - tags
