image: maven:3.6-jdk-11

cache:
  paths:
    - maven.repository/

variables:
  MAVEN_OPTS: "--batch-mode -Dmaven.repo.local=maven.repository -s ci_settings.xml"
 
buildTestAndDeploy:
  stage: deploy
  script:
    - mvn deploy
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"
        - "**/target/failsafe-reports/TEST-*.xml"
  allow_failure: true

generate-coverage:
  stage: .post
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
  needs: ["buildTestAndDeploy"]
  dependencies:
    - buildTestAndDeploy
  artifacts:
    reports:
      cobertura: target/site/cobertura.xml
  allow_failure: true

publish:
  stage: .post
  script:
    - mv target/generated-docs public
  artifacts:
    paths:
      - public
  allow_failure: true