/*
 * -----------------------------------------------------------------------------
 *
 * Copyright (c) 2019 - 2022 UDT-IA, IIIA-CSIC
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * -----------------------------------------------------------------------------
 */

package eu.internetofus.common.components.profile_manager;

import java.util.UUID;

import eu.internetofus.common.components.Mergeable;
import eu.internetofus.common.components.Merges;
import eu.internetofus.common.components.Model;
import eu.internetofus.common.components.Validable;
import eu.internetofus.common.components.ValidationErrorException;
import eu.internetofus.common.components.Validations;
import io.swagger.v3.oas.annotations.media.Schema;
import io.vertx.core.Future;
import io.vertx.core.Promise;
import io.vertx.core.Vertx;

/**
 * A location of interest for the user, may be the home or work location. This
 * information is generated by the platform AI.
 *
 * @author UDT-IA, IIIA-CSIC
 */
@Schema(
		description = "A location of interest for the user - may be the home or work location -. This information is generated by the platform AI.")
public class RelevantLocation extends Model implements Validable, Mergeable<RelevantLocation> {

	/**
	 * The identifier of the relevant location.
	 */
	@Schema(description = "The identifier of the location", example = "kdjfghd8hikdfg")
	public String id;

	/**
	 * The descriptor of the location.
	 */
	@Schema(description = "The descriptor of the location", example = "Home")
	public String label;

	/**
	 * The latitude of the location.
	 */
	@Schema(description = "The latitude of the location", example = "40.388756")
	public double latitude;

	/**
	 * The longitude of the location.
	 */
	@Schema(description = "The longitude of the location", example = "-3.588622")
	public double longitude;

	/**
	 * Create an empty relation.
	 */
	public RelevantLocation() {

	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Future<Void> validate(String codePrefix, Vertx vertx) {

		final Promise<Void> promise = Promise.promise();
		try {

			this.id = Validations.validateNullableStringField(codePrefix, "id", 255, this.id);
			if (this.id != null) {

				promise.fail(new ValidationErrorException(codePrefix + ".id",
						"You can not specify the identifier of the relevant location to create"));

			} else {

				this.id = UUID.randomUUID().toString();
				this.label = Validations.validateNullableStringField(codePrefix, "label", 255, this.label);
				if (this.latitude < -90 || this.latitude > 90) {

					promise.fail(
							new ValidationErrorException(codePrefix + ".latitude", "The latitude has to be on the range [-90,90]"));

				} else if (this.longitude < -180 || this.longitude > 180) {

					promise.fail(new ValidationErrorException(codePrefix + ".longitude",
							"The longitude has to be on the range [-180,180]"));

				} else {

					promise.complete();
				}
			}

		} catch (final ValidationErrorException validationError) {

			promise.fail(validationError);
		}

		return promise.future();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Future<RelevantLocation> merge(RelevantLocation source, String codePrefix, Vertx vertx) {

		final Promise<RelevantLocation> promise = Promise.promise();
		Future<RelevantLocation> future = promise.future();
		if (source != null) {

			final RelevantLocation merged = new RelevantLocation();
			merged.label = source.label;
			if (merged.label == null) {

				merged.label = this.label;
			}
			merged.latitude = source.latitude;
			merged.longitude = source.longitude;

			promise.complete(merged);

			// validate the merged value and set the id
			future = future.compose(Merges.validateMerged(codePrefix, vertx)).map(mergedValidatedModel -> {

				mergedValidatedModel.id = this.id;
				return mergedValidatedModel;
			});

		} else {

			promise.complete(this);

		}
		return future;
	}

}
